Develop/system test
ArthurAtangana/SYSC3303A_Project pull request #54
Opened 2024-02-19 21:07 UTC by ArthurAtangana

2024-02-20 16:45 UTC, orselane requested changes

2024-02-20 16:45 UTC, orselane commented on src/Messaging/Receivers/DMA_Receiver.java
>      public synchronized SystemMessage receive() {
Remove synchronized keyword (already synchronized on msgBuf inside)

2024-02-20 16:45 UTC, orselane commented on src/SchedulerSubsystem/Loader.java
> +        //System.out.println("loader: ask passengers from the floor");
Remove commented out code (check prints in all changed files please.)

2024-02-20 16:45 UTC, orselane commented on src/SchedulerSubsystem/Scheduler.java
> +import java.util.*;
Auto-import should only import the needed classes, why is this a wildcard?

2024-02-20 16:45 UTC, orselane commented on src/SchedulerSubsystem/Scheduler.java
> +        if (e.passengerCountMap().isEmpty() && getElevatorDirection(e) != getOldestFloorRequest().direction()){
This condition should either be a named boolean private method, or commented

2024-02-20 16:48 UTC, orselane commented
Also, there is no system test file. This PR does not modify the system test file, if the PR has a "Yes" for test, shouldn't we have something in the How to Test section?

2024-02-23 20:59 UTC, orselane approved these changes

2024-02-24 00:32 UTC, mpdesantis approved these changes
You busy guy. Looks really nice, and I like the test scenarios. :)

2024-02-24 01:01 UTC, merged